# Generated by Django 4.1.7 on 2023-02-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complet_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nome Completo"
                    ),
                ),
                ("cpf", models.CharField(max_length=14, null=True, verbose_name="CPF")),
                (
                    "phone",
                    models.CharField(max_length=16, null=True, verbose_name="Telefone"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
