# Generated by Django 4.1.7 on 2023-02-23 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cpf",
            field=models.CharField(
                max_length=14,
                null=True,
                validators=[django.core.validators.MinLengthValidator(14)],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=16,
                null=True,
                validators=[django.core.validators.MinLengthValidator(15)],
                verbose_name="Telefone",
            ),
        ),
    ]
