# Generated by Django 4.1.7 on 2023-02-23 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_cpf_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=16,
                null=True,
                validators=[django.core.validators.MinLengthValidator(14)],
                verbose_name="Telefone",
            ),
        ),
    ]
