# Generated by Django 4.1.7 on 2023-02-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="details",
            field=models.CharField(max_length=100, null=True, verbose_name="Detalhes"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="records.field",
                verbose_name="Campo",
            ),
        ),
    ]
