# Generated by Django 4.1.7 on 2023-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_activity_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="details",
            field=models.CharField(max_length=100, verbose_name="Detalhes"),
        ),
    ]
