# Generated by Django 4.1.7 on 2023-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_alter_activity_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="number",
            field=models.IntegerField(help_text="Digita corno", verbose_name="Número"),
        ),
    ]
