# Generated by Django 4.1.7 on 2023-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0005_alter_activity_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="number",
            field=models.IntegerField(verbose_name="Número"),
        ),
    ]
