# Generated by Django 4.1.7 on 2023-02-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_alter_activity_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["number"], "verbose_name": "Atividade"},
        ),
        migrations.AlterModelOptions(
            name="field", options={"ordering": ["name"], "verbose_name": "Campo"},
        ),
    ]
