# Generated by Django 4.1.7 on 2023-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0009_activity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="file",
            field=models.FileField(default=1, upload_to="pdf/"),
            preserve_default=False,
        ),
    ]
