# Generated by Django 4.1.7 on 2023-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0010_activity_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="file",
            field=models.FileField(upload_to="pdf/", verbose_name="Arquivo"),
        ),
    ]
